### PR TITLE
[MIG] web_tree_dynamic_colored_field

### PR DESCRIPTION
**Pull request by Herqs**

### CODE REVIEW

**Comment by oerp-odoo** [comment]
@Herqs  So it works out of the box?

**Review by SButko — APPROVED** [review]

**Review by SButko — COMMENTED** [review]
Shouldn't PR be pointed to 15-ea?

**Comment by Herqs** [comment]
> Shouldn't PR be pointed to 15-ea?

@SButko  There is no `15-ea`  branch on `web-oca` repo. Should I create `15-ea` and point this PR to it ?

> @Herqs So it works out of the box?

@oerp-odoo Yes. But some features were removed in v13 and onwards. Specifically the `color` attribute on tree view definition is not supported anymore due to changes in RelaxNG schema of the tree view. As we're migrating from v12, we should check if we use this functionality anywhere.
More info with feature removal commits in ROADMAP.rst

**Comment by oerp-odoo** [comment]
@Herqs yes, create that branch please. 15.0 should be used to keep same commits as in oca.

**Review by oerp-odoo — APPROVED** [review]

**Pull request merged**
